development:
  cloud_name: dgsob9jcr
  api_key: '569483889916288'
  api_secret: 3mvrBKBDPFJOJm6oQPX9gmwcMGE
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dgsob9jcr
  api_key: '569483889916288'
  api_secret: 3mvrBKBDPFJOJm6oQPX9gmwcMGE
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dgsob9jcr
  api_key: '569483889916288'
  api_secret: 3mvrBKBDPFJOJm6oQPX9gmwcMGE
  enhance_image_tag: true
  static_file_support: false
